### ISSUE TITLE
How to add or remove SubAgent when the server is runing

### ISSUE THREAD

**Issue by RainyBow** [slayercat/GoSNMPServer#11]
How to add or remove SubAgent  or User when the server is runing

**Comment by slayercat** [comment]
Well……Multithreading and locking  is not fully consided. For a quick start, i'll suggest an atomic operation to fully replace `MasterAgent`, for the server do not have a state, so it shell works fine.

**Comment by RainyBow** [comment]
thanks, I change the master to Master  ，it works fine.
