### ISSUE TITLE
How do I solve the concurrency problem

### ISSUE THREAD

**Issue by Chien-W** [slayercat/GoSNMPServer#12]
I found that after receiving the packet from the network, the code in the warehouse seems to execute each event in a single step. Is there a high concurrency problem in the library? After the network packet is unwrapped, can each event independently open a coroutine to complete the logic of data acquisition in its own business and then return to the other party?

**Comment by Chien-W** [comment]
Hello, that is to say, I need to improve the ability to handle traffic, so I can only modify your library and add coroutines to accelerate the processing of business logic. Your library does not do coroutine forwarding, right？

**Comment by slayercat** [comment]
Thank you for ask, and I would appreciate it if you would like to contribute your implementation.

**Comment by Chien-W** [comment]
I added a simple coroutine pool to ensure coroutine processing of transactions. I tested it a little and it seems to be fine. I'm not sure if it triggers any special bugs.

**Comment by slayercat** [comment]
Thank you very much for your contribution. I have carefully considered it, but I still believe that handling concurrency through multiple Goroutines in Golang is the responsibility of the library's users. Therefore, I regret to inform you that I cannot accept this modification.

If you have any feedback or suggestions, or if you would like to provide a demo or sample program, please feel free to engage in further discussion.
