### ISSUE TITLE
How can I set up a ro/rw community? 

### ISSUE THREAD

**Issue by boykostass** [slayercat/GoSNMPServer#18]
How can I set up a ro/rw community?

**Comment by slayercat** [comment]
Thank you for your question.

In this repository, we provide a skeleton for building an SNMP server using Golang. It serves as a foundation that you can use to create your own SNMP server implementation.

The handler within the server is responsible for checking permissions and determining what actions can be performed. The pre-provided MIB (Management Information Base) definitions in the mibImps/mibImps.go file are implemented as read-only. They are intended to be used as a demo or starting point for your implementation.

To modify the system status or enable read-write functionality, you can extend the handler code and customize it according to your requirements.

We hope this clarifies the purpose and usage of this repository. If you have any further questions, please let us know.
