### ISSUE TITLE
Getnext request multiple oids: incorrect behavior

### ISSUE THREAD

**Issue by adenis78** [slayercat/GoSNMPServer#19]
From wireshark analyzer:
get-next-request 1.3.6.1.2.1.33.1.3.3.1.1 1.3.6.1.2.1.33.1.3.3.1.2 1.3.6.1.2.1.33.1.3.3.1.3 1.3.6.1.2.1.33.1.3.3.1.4 1.3.6.1.2.1.33.1.3.3.1.5
get-response 1.3.6.1.2.1.33.1.3.3.1.5.0 1.3.6.1.2.1.33.1.3.3.1.5.1 1.3.6.1.2.1.33.1.3.3.1.5.2 1.3.6.1.2.1.33.1.4.1.0 1.3.6.1.2.1.33.1.4.2.05

After get-next-request with multiple oids: gosnmpserver get LAST oid (1.3.6.1.2.1.33.1.3.3.1.4) from the end of oid list. Then response is .3.6.1.2.1.33.1.3.3.1.5.0 (next after 1.3.6.1.2.1.33.1.3.3.1.4), not after 1.3.6.1.2.1.33.1.3.3.1.1 (1.3.6.1.2.1.33.1.3.3.1.1.1...5).
It's happened after  table request. NetSnmp utilities now use get-bulk-request in gettable cli , and all is ok (no error). But some software is continue to use old style (was in SNMP v1)  and error occurs.

P.S. "some software" is iReasoning Mib Browser. It's useful and valuable for many users. Table View does not work.

**Comment by slayercat** [comment]
I apologize for not noticing this issue earlier.

The commit https://github.com/slayercat/GoSNMPServer/commit/f220d18995267b7e1ad44a23fb1239e6741eeaa1 might fixed the issue you mentioned. Please feel free to give it a try.

**Comment by adenis78** [comment]
It's alright now. Thanks!

**Comment by adenis78** [comment]
(... but this corrected version 0.4 (with a tag) can only be used from the archive. I can't get it using go.mod)
