### ISSUE TITLE
ERROR: Not Find eth VHC128

### ISSUE THREAD

**Issue by Grishy** [slayercat/GoSNMPServer#2]
Hi,

Try to run on macOS and get some errors:
![image](https://user-images.githubusercontent.com/13949080/74732180-bb3b9580-525a-11ea-9407-8e3b5db8e52c.png)

```
git log -1 --oneline
5f6bb8b (HEAD -> master, tag: v0.1.1, origin/master, origin/HEAD) mibsImps: small type fix to make mibs righ
````

System:
[system_report_basic.txt](https://github.com/slayercat/GoSNMPServer/files/4218938/system_report_basic.txt)

**Comment by slayercat** [comment]
Thanks for your report.

I've made a commit to try to fix it. see commit  150864f

However, I do not have a macOS  in touch. Would you mind to have it a try?

**Comment by Grishy** [comment]
Yea, 
I checked and it's work fine!
