### ISSUE TITLE
Tags > 0.1.2 are not valid semver versions

### ISSUE THREAD

**Issue by steelshot** [slayercat/GoSNMPServer#25]
The tags applied after 0.1.2 are invalid and the pkg.go.dev is ignoring them. You currently have to use direct commit refs to pull later versions than 0.1.2.

Reference: [pkg.go.dev](https://pkg.go.dev/github.com/slayercat/GoSNMPServer?tab=versions)

`
go get github.com/slayercat/GoSNMPServer@v0.4

go: github.com/slayercat/GoSNMPServer@v0.4: no matching versions for query "v0.4"
`

**Comment by slayercat** [comment]
Thank you very much for raising this issue. I apologize for not having noticed this problem before.

I have now uploaded new tags that comply with the Semantic Versioning  guidelines (v0.4.0 and v0.5.0). Please give them a try.

I've successfully verified it  using the following command:


`go install github.com/slayercat/GoSNMPServer/cmd/gosnmpserver@v0.5.0`

**Comment by steelshot** [comment]
That seems to be working as expected now. No need to apologize, the go tool/pkg.go.dev could report things better.
