### ISSUE TITLE
SNMPv2c does not work anymore (ErrNoPermission)

### ISSUE THREAD

**Issue by vincentbernat** [slayercat/GoSNMPServer#28]
```
$ go run github.com/slayercat/GoSNMPServer/cmd/gosnmpserver@v0.5.1 run-server --community public
$ snmpwalk -v2c -c public 127.0.0.1:1161
[...]
INFO[0000] ListenUDP: l3proto=udp, address=127.0.0.1:1161
INFO[0002] udp request from 127.0.0.1:39858. size=40
WARN[0002] ResponseForBuffer Error: ErrNoPermission. without result
INFO[0003] udp request from 127.0.0.1:39858. size=40
WARN[0003] ResponseForBuffer Error: ErrNoPermission. without result
INFO[0004] udp request from 127.0.0.1:39858. size=40
WARN[0004] ResponseForBuffer Error: ErrNoPermission. without result
```

Dunno if it's related to #27 and #23. It does not work with 0.5 either.

**Comment by slayercat** [comment]
Thank you very much for dedicating your time to identify this issue. We sincerely apologize for the inconvenience caused due to the lack of comprehensive testing previously.

We have released a new version addressing the problem you highlighted. Thanks for try it out.

**Comment by slayercat** [comment]
I believe that with the release of the new version, this issue has been resolved. If the problem persists, please feel free to reopen this issue or create a new one.
