### ISSUE TITLE
go mod tidy

### ISSUE THREAD

**Issue by pierreyves258** [slayercat/GoSNMPServer#6]
Hi,
When i do a go mod tidy on my project using GoSNMPServer I got this error

```
go: found github.com/soniah/gosnmp in github.com/soniah/gosnmp v1.34.0
go: ./services imports
        github.com/slayercat/gosnmp tested by
        github.com/slayercat/gosnmp.test imports
        github.com/soniah/gosnmp: github.com/soniah/gosnmp@v1.34.0: parsing go.mod:
        module declares its path as: github.com/gosnmp/gosnmp
                but was required as: github.com/soniah/gosnmp
```
I think it comes form the fact that github.com/soniah/gosnmp is now github.com/gosnmp/gosnmp but I don't know how to fix it

Thanks

**Comment by pierreyves258** [comment]
I thinks this may fix the issue https://github.com/slayercat/gosnmp/pull/1

**Comment by slayercat** [comment]
thanks for submitting this ticket~ the MR you mentioned has been merged. would you mind to have it a test?

**Comment by vincentbernat** [comment]
It works for me.

**Comment by slayercat** [comment]
thansk~

**Comment by vincentbernat** [comment]
No version was released with a fix. You need to add this to `go.mod`:

```
replace github.com/slayercat/gosnmp => github.com/slayercat/gosnmp v1.24.1-0.20220124233957-4b805977d286
```

**Comment by slayercat** [comment]
Thanks for your comment, Just made a release to fix it.  @vincentbernat @harenber 
 
Please feel free to reopen or file a new issue if you are encountering a similar or related problem.
